export const endpoints = {
  login: "api/admin/login",
  complaints: "api/admin/get-complaints",
  technician: "api/admin/get-engineers",
  customer: "api/admin/get-customers",
  dashboard: "api/admin/get-stats",
  project: "api/admin/get-project",
  singleProject: "api/admin/get-single-project",
  addProject: "api/admin/add-project",
  patchTechnician: "api/admin/add-technican",
  warranty: "api/admin/get-all-warranty",
  amc: "api/admin/get-all-amc",
  createWarranty: "api/admin/generate-warranty",
  getWarranty: "api/admin/get-warranty",
  editWarranty: "api/admin/edit-warranty",
  createAmc: "api/admin/generate-amc",
  getAmc: "api/admin/get-amc",
  editAmc: "api/admin/edit-amc",
  notifications: "api/admin/get-all-notification",
  changePassword: "api/admin/change-password",
};
